services:

  backend:
    container_name: dvt-backend-dev
    image: dvt-backend:dev
    build: 
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
    command: tail -f /dev/null

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./backend/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"